### ISSUE TITLE
Erro: "Situação inválida"

### ISSUE THREAD

**Issue by evertonpavan** [IFRS/pagif#1]
Ao tentar consultar um código de pagamento já gerado, retorna o erro "Situação inválida".

![erro-situacao-invalida](https://user-images.githubusercontent.com/13000485/228344579-b7229227-eb03-464c-90ef-f905d1921854.png)

**Comment by ricardomoro** [comment]
Olá @evertonpavan.

Isso acontece quando a tela de pagamento do PagTesouro já foi acessada pelo menos uma vez.
Na [documentação da API do PagTesouro](https://valpagtesouro.tesouro.gov.br/simulador/#/pages/api) (seção 3) tem essa explicação:

> A URL retornada na Resposta anterior (atributo proximaUrl) só poderá ser acionada uma única vez. Caso a mesma URL seja novamente acionada, o PagTesouro exibirá a mensagem "Situação inválida".

Infelizmente é um comportamento do PagTesouro, não há nada que possamos fazer para contornar isso. Porém, após a atualização da "situação" do pagamento, o sistema não permite mais o carregamento da tela do PagTesouro, evitando essa situação.

**Comment by evertonpavan** [comment]
@ricardomoro Entendi! A própria API do PagTesouro bloqueia uma 2ª consulta.

Os usuários do campus estavam relatando esse "problema".

Como sugestão(se for possível e adequado):

Deixar claro ao usuário que a tela de pagamento do PagTesouro(onde aparece as opções: PIX, Cartão de crédito e Boleto GRU) só será exibida uma vez para cada código gerado.

- Adicionar um snackbar(na tela abaixo):
![last-page-to-paymnet](https://user-images.githubusercontent.com/13000485/228579894-ba67bee3-23a7-4a62-9439-ca84921ce9a4.png)

- Adicionar dialog/modal após clicar nos botões em Pagar e Pagar Agora nas respectivas telas abaixo:
![before-click-pagar](https://user-images.githubusercontent.com/13000485/228585200-bb93f567-cd5f-4340-bdd3-100c770d2b8b.png)

![before-click-pagar-agora](https://user-images.githubusercontent.com/13000485/228585135-a5918af3-99e6-4fb9-a7ac-85bb00d28221.png)

**Comment by ricardomoro** [comment]
Pois é. Se tu reparar bem, no alerta amarelo na tela de pagamento o aviso fala exatamente sobre isso.

Não adianta colocar aviso depois de carregar a tela do PagTesouro (com as opções de pagamento) pois já seria tarde demais para fazer qualquer coisa. E também, não adianta colocar o aviso no dialog com a confirmação de criação do pagamento, pois a tela com os dados do pagamento PODE ser acessada mais de uma vez.

Talvez eu mude a cor do alerta para vermelho, para chamar mais a atenção sobre a informação de que a ação "Pagar Agora" só pode ser realizada uma única vez. Por enquanto só consigo pensar nessa solução...
